Algoritmo "Exercicio01.Estrutura_de_Repeticao"
// Descrição   : imprimir 10 vezes o nome da disciplina
// Autor(a)    : Gabriela Gomes da Fonseca

Var
// Seção de Declarações das variáveis 
disciplina: cadeia
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o nome de uma disciplina: ")
leia(disciplina)

para i de 1 ate 10 faca
     escreva(disciplina)
fim_para

Fimalgoritmo