Algoritmo "Exercicio14.Estrutura_de_Repeticao"
// Descrição   : imprimir os números pares entre 8 e 18
// Autor(a)    : Gabriela Gomes da Fonseca

Var
// Seção de Declarações das variáveis
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 8 ate 18 passo 1 faca
     se (i mod 2 = 0) entao
        escreva(i)
     fim_se
fim_para

Fimalgoritmo